[metadata.heroku]
  root-package = "github.com/ob-vss-ss18/ppl-leasing"
[[constraint]]
  name = "github.com/graphql-go/graphql"
  version = "0.7.5"

[[constraint]]
  name = "github.com/graphql-go/handler"
  version = "0.2.1"
